In [42]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import nltk

In [43]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

In [44]:
import chardet

with open("mail.csv", 'rb') as f:
    result = chardet.detect(f.read())

print(result)

{'encoding': 'Windows-1252', 'confidence': 0.7257971165545478, 'language': ''}

In [45]:
df = pd.read_csv("mail.csv", encoding='Windows-1252')

In [46]:
df

        v1                                                 v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      ham  Go until jurong point, crazy.. Available only ...        NaN        NaN        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN        NaN        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN        NaN
3      ham  U dun say so early hor... U c already then say...        NaN        NaN        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN        NaN        NaN
...    ...                                                ...        ...        ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN        NaN        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN        NaN        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN        NaN        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN        NaN        NaN
5571   ham                         Rofl. Its true to its name        NaN        NaN        NaN

[5572 rows x 5 columns]

In [47]:
unwanted_columns  = ["Unnamed: 2",	"Unnamed: 3",	"Unnamed: 4"]
df.drop(columns = unwanted_columns , inplace= True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [48]:
column_new_name = {"v1": "category" , "v2":"Message"}
df.rename(columns=column_new_name , inplace = True)
df.head()

  category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [49]:
df.isnull().sum()

category    0
Message     0
dtype: int64

In [50]:
df['category'].value_counts()

category
ham     4825
spam     747
Name: count, dtype: int64

In [51]:
unique_message = df['category'].unique()
message_numbers = {}
i = 0 
for mes in unique_message:
    message_numbers[mes] = i
    i+=1

df['category'] = df['category'].map(message_numbers)

In [52]:
df

      category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0              Will Ì_ b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [53]:
df['category'].value_counts()

category
0    4825
1     747
Name: count, dtype: int64

In [54]:
#lowercasing 
df['Message'] = df['Message'].apply(lambda x:x.lower())

In [57]:
#remove puncuation 
import string 
def remove_punc(Message):
    return Message.translate(str.maketrans('','',string.punctuation))

In [58]:
df['Message'] = df['Message'].apply(remove_punc)

In [62]:
#Remove Numbers 
def remove_numbers(Message):
    new =""
    for i in Message:
        if not i.isdigit():
            new =new+i
    return new 
df['Message'] = df['Message'].apply(remove_numbers)

In [65]:
#removing urls
import re

def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

In [66]:
df['Message'] = df['Message'].apply(remove_urls)

In [68]:
#Remove emojies 
def remove_emojis(text):
    return re.sub(r'[^\x00-\x7F]+', '', text)

In [69]:
df['Message'] = df['Message'].apply(remove_emojis)

In [70]:
#Remove special characters 
def remove_special_chars(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

In [71]:
df['Message'] = df['Message'].apply(remove_special_chars)

In [73]:
df

      category                                            Message
0            0  go until jurong point crazy available only in ...
1            0                            ok lar joking wif u oni
2            1  free entry in  a wkly comp to win fa cup final...
3            0        u dun say so early hor u c already then say
4            0  nah i dont think he goes to usf he lives aroun...
...        ...                                                ...
5567         1  this is the nd time we have tried  contact u u...
5568         0                 will  b going to esplanade fr home
5569         0  pity  was in mood for that soany other suggest...
5570         0  the guy did some bitching but i acted like id ...
5571         0                          rofl its true to its name

[5572 rows x 2 columns]

In [75]:
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [76]:
stopwords = set(stopwords.words("english"))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [77]:
len(stopwords)

198

In [82]:
# lets tokenize 
def remove(Message):
    if isinstance(Message , str): 
        words = word_tokenize(Message)
        cleaned =[]
        for i in words: 
            if i not in stopwords: 
                cleaned.append(i) 
        return ' '.join(cleaned)
    return Message

In [83]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [84]:
df['Message'] = df['Message'].apply(remove)

In [88]:
df.loc[1]['Message']

'ok lar joking wif u oni'

In [89]:
df.loc[2]['Message']

'free entry wkly comp win fa cup final tkts st may text fa receive entry questionstd txt ratetcs apply overs'

In [90]:
df.loc[3]['Message']

'u dun say early hor u c already say'

In [91]:
#model 
from sklearn.model_selection import train_test_split

In [92]:
x = df['Message']
y = df['category']
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [93]:
#let use bag of words 
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer
from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import accuracy_score

In [95]:
bag = CountVectorizer()
x_train_bag = bag.fit_transform(x_train)
x_test_bag = bag.transform(x_test)

In [96]:
model_1 = MultinomialNB()
model_1.fit(x_train_bag , y_train)

MultinomialNB()

In [97]:
predict_bag = model_1.predict(x_test_bag)

In [98]:
accuracy_score(y_test , predict_bag)

0.9802690582959641

In [100]:
# using TfidfVectorizer
tfidf = TfidfVectorizer() 
x_train_tfidf = tfidf.fit_transform(x_train) 
x_test_tfidf = tfidf.transform(x_test)

In [101]:
model_2 = MultinomialNB()
model_2.fit(x_train_tfidf , y_train)

MultinomialNB()

In [102]:
predict_tfidf = model_2.predict(x_test_tfidf)

In [103]:
accuracy_score(y_test , predict_tfidf)

0.968609865470852

In [104]:
#logestic regression use 
from sklearn.linear_model import LogisticRegression

In [105]:
logestic = LogisticRegression(max_iter=1000)
logestic.fit(x_train_tfidf , y_train)

LogisticRegression(max_iter=1000)

In [106]:
predict_logestic_tfidf = logestic.predict(x_test_tfidf)

In [107]:
accuracy_score(y_test , predict_logestic_tfidf)

0.9506726457399103

In [108]:
#logestic using bag of words

In [109]:
logestic_bag = LogisticRegression(max_iter=1000)
logestic_bag.fit(x_train_bag , y_train)

LogisticRegression(max_iter=1000)

In [110]:
predict_logestic_bag = logestic_bag.predict(x_test_bag)

In [111]:
accuracy_score(y_test , predict_logestic_bag)

0.9766816143497757

In [117]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict_bag))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       965
           1       0.96      0.89      0.92       150

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [118]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict_tfidf))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.77      0.87       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.93      1115
weighted avg       0.97      0.97      0.97      1115

In [121]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict_logestic_tfidf))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       965
           1       0.96      0.66      0.78       150

    accuracy                           0.95      1115
   macro avg       0.96      0.83      0.88      1115
weighted avg       0.95      0.95      0.95      1115

In [122]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict_logestic_bag))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       965
           1       1.00      0.83      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [126]:
import joblib
import pickle

In [127]:
pickle.dump(model_1, open("model_1.pkl", "wb"))

In [130]:
pickle.dump(bag, open("vectorizer.pkl", "wb"))